// Mocks generated by Mockito 5.4.6 from annotations
// in phero_app/test/domain/usecases/submit_new_report_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phero_app/domain/models/app_user.dart' as _i10;
import 'package:phero_app/domain/models/captured_media.dart' as _i8;
import 'package:phero_app/domain/models/location_data.dart' as _i6;
import 'package:phero_app/domain/models/report.dart' as _i4;
import 'package:phero_app/domain/repositories/auth_repository.dart' as _i9;
import 'package:phero_app/domain/repositories/camera_service.dart' as _i7;
import 'package:phero_app/domain/repositories/location_service.dart' as _i5;
import 'package:phero_app/domain/repositories/report_repository.dart' as _i2;
import 'package:phero_app/domain/repositories/storage_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportRepository extends _i1.Mock implements _i2.ReportRepository {
  MockReportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createReport(_i4.Report? report) =>
      (super.noSuchMethod(
            Invocation.method(#createReport, [report]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Report>> getReports() =>
      (super.noSuchMethod(
            Invocation.method(#getReports, []),
            returnValue: _i3.Future<List<_i4.Report>>.value(<_i4.Report>[]),
          )
          as _i3.Future<List<_i4.Report>>);

  @override
  _i3.Future<List<_i4.Report>> getUserReports(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReports, [userId]),
            returnValue: _i3.Future<List<_i4.Report>>.value(<_i4.Report>[]),
          )
          as _i3.Future<List<_i4.Report>>);

  @override
  _i3.Future<void> updateReportStatus(String? reportId, String? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#updateReportStatus, [reportId, newStatus]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteReport(String? reportId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReport, [reportId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Report>> getReportsNearby({
    required double? latitude,
    required double? longitude,
    required double? radiusInKm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReportsNearby, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusInKm: radiusInKm,
            }),
            returnValue: _i3.Future<List<_i4.Report>>.value(<_i4.Report>[]),
          )
          as _i3.Future<List<_i4.Report>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i5.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkAndRequestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkAndRequestPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i6.LocationData?> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i3.Future<_i6.LocationData?>.value(),
          )
          as _i3.Future<_i6.LocationData?>);
}

/// A class which mocks [CameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraService extends _i1.Mock implements _i7.CameraService {
  MockCameraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i8.CapturedMedia?> takePicture() =>
      (super.noSuchMethod(
            Invocation.method(#takePicture, []),
            returnValue: _i3.Future<_i8.CapturedMedia?>.value(),
          )
          as _i3.Future<_i8.CapturedMedia?>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i10.AppUser?> get userChanges =>
      (super.noSuchMethod(
            Invocation.getter(#userChanges),
            returnValue: _i3.Stream<_i10.AppUser?>.empty(),
          )
          as _i3.Stream<_i10.AppUser?>);

  @override
  _i3.Future<_i10.AppUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i10.AppUser?>.value(),
          )
          as _i3.Future<_i10.AppUser?>);

  @override
  _i3.Future<_i10.AppUser?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i10.AppUser?>.value(),
          )
          as _i3.Future<_i10.AppUser?>);

  @override
  _i3.Future<_i10.AppUser?> createUserWithEmailAndPassword(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
              displayName,
            ]),
            returnValue: _i3.Future<_i10.AppUser?>.value(),
          )
          as _i3.Future<_i10.AppUser?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i11.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> uploadReportImage(
    String? userId,
    String? reportId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadReportImage, [userId, reportId, filePath]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
