// Mocks generated by Mockito 5.4.6 from annotations
// in phero_app/test/domain/usecases/update_report_status_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phero_app/domain/models/report.dart' as _i4;
import 'package:phero_app/domain/repositories/report_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportRepository extends _i1.Mock implements _i2.ReportRepository {
  MockReportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createReport(_i4.Report? report) =>
      (super.noSuchMethod(
            Invocation.method(#createReport, [report]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Report>> getReports() =>
      (super.noSuchMethod(
            Invocation.method(#getReports, []),
            returnValue: _i3.Future<List<_i4.Report>>.value(<_i4.Report>[]),
          )
          as _i3.Future<List<_i4.Report>>);

  @override
  _i3.Future<List<_i4.Report>> getUserReports(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReports, [userId]),
            returnValue: _i3.Future<List<_i4.Report>>.value(<_i4.Report>[]),
          )
          as _i3.Future<List<_i4.Report>>);

  @override
  _i3.Future<void> updateReportStatus(String? reportId, String? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#updateReportStatus, [reportId, newStatus]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteReport(String? reportId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReport, [reportId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Report>> getReportsNearby({
    required double? latitude,
    required double? longitude,
    required double? radiusInKm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReportsNearby, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusInKm: radiusInKm,
            }),
            returnValue: _i3.Future<List<_i4.Report>>.value(<_i4.Report>[]),
          )
          as _i3.Future<List<_i4.Report>>);
}
