// Mocks generated by Mockito 5.4.6 from annotations
// in phero_app/test/features/admin/admin_dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phero_app/domain/models/app_user.dart' as _i4;
import 'package:phero_app/domain/models/report.dart' as _i7;
import 'package:phero_app/domain/repositories/auth_repository.dart' as _i2;
import 'package:phero_app/domain/usecases/delete_report_usecase.dart' as _i10;
import 'package:phero_app/domain/usecases/fetch_nearby_reports_usecase.dart'
    as _i8;
import 'package:phero_app/domain/usecases/fetch_reports_usecase.dart' as _i6;
import 'package:phero_app/domain/usecases/submit_new_report_usecase.dart'
    as _i5;
import 'package:phero_app/domain/usecases/update_report_status_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.AppUser?> get userChanges =>
      (super.noSuchMethod(
            Invocation.getter(#userChanges),
            returnValue: _i3.Stream<_i4.AppUser?>.empty(),
          )
          as _i3.Stream<_i4.AppUser?>);

  @override
  _i3.Future<_i4.AppUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i4.AppUser?>.value(),
          )
          as _i3.Future<_i4.AppUser?>);

  @override
  _i3.Future<_i4.AppUser?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i4.AppUser?>.value(),
          )
          as _i3.Future<_i4.AppUser?>);

  @override
  _i3.Future<_i4.AppUser?> createUserWithEmailAndPassword(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
              displayName,
            ]),
            returnValue: _i3.Future<_i4.AppUser?>.value(),
          )
          as _i3.Future<_i4.AppUser?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SubmitNewReportUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitNewReportUseCase extends _i1.Mock
    implements _i5.SubmitNewReportUseCase {
  MockSubmitNewReportUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute({
    required String? title,
    required String? description,
    bool? capturePhoto = false,
    String? localImagePath,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #title: title,
              #description: description,
              #capturePhoto: capturePhoto,
              #localImagePath: localImagePath,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FetchReportsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchReportsUseCase extends _i1.Mock
    implements _i6.FetchReportsUseCase {
  MockFetchReportsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.Report>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<List<_i7.Report>>.value(<_i7.Report>[]),
          )
          as _i3.Future<List<_i7.Report>>);

  @override
  _i3.Future<List<_i7.Report>> executeForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#executeForUser, [userId]),
            returnValue: _i3.Future<List<_i7.Report>>.value(<_i7.Report>[]),
          )
          as _i3.Future<List<_i7.Report>>);
}

/// A class which mocks [FetchNearbyReportsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchNearbyReportsUseCase extends _i1.Mock
    implements _i8.FetchNearbyReportsUseCase {
  MockFetchNearbyReportsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.Report>> execute({
    required double? latitude,
    required double? longitude,
    required double? radiusInKm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusInKm: radiusInKm,
            }),
            returnValue: _i3.Future<List<_i7.Report>>.value(<_i7.Report>[]),
          )
          as _i3.Future<List<_i7.Report>>);
}

/// A class which mocks [UpdateReportStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateReportStatusUseCase extends _i1.Mock
    implements _i9.UpdateReportStatusUseCase {
  MockUpdateReportStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute(String? reportId, String? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [reportId, newStatus]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DeleteReportUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteReportUseCase extends _i1.Mock
    implements _i10.DeleteReportUseCase {
  MockDeleteReportUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute(String? reportId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [reportId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
